# Generated by Django 5.2.5 on 2025-09-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_question_option4'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleplayer', models.CharField(max_length=10)),
                ('multiplayer', models.CharField(max_length=10)),
            ],
        ),
    ]
