# Generated by Django 5.2.6 on 2025-09-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
    ]
