name: Verify

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Verify Linting and Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: futureofmemory/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: futureofmemory/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run check
